server {
    listen 80;
    server_name pg.jpgonzalez.dev;

    client_max_body_size 200M;

    # redirige todo a https
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name pg.jpgonzalez.dev;

    ssl_certificate /etc/letsencrypt/live/pg.jpgonzalez.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pg.jpgonzalez.dev/privkey.pem;

    proxy_buffering off;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;

    client_max_body_size 200M;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /static_collected/;
    }

    location /media/ {
        alias /media/;
    }

    # WebSockets
    location /chat/ {
        proxy_pass http://web:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /ws/ {
        proxy_pass http://web:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /notifications/ {
        proxy_pass http://web:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}